providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd client && npm ci"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd client && npm start"
